name: AWS / LocalStack Airflow Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-pods-load:  
    runs-on: ubuntu-latest
    steps:
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          use-pro: 'true'
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
      - name: Load the Cloud Pod
        continue-on-error: true # Allow it to fail as pod does not exist at first run
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          state-backend: cloud-pods
          state-name: pod-test-gio-3
          state-action: load
          skip-startup: 'true'